apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secrets
  namespace: notification
type: Opaque
data:
  spring-datasource-username: cG9zdGdyZXM= # postgres
  spring-datasource-password: cGFzc3dvcmQ= # password
  smtp-username: eW91ci1lbWFpbEBnbWFpbC5jb20= # your-email@gmail.com
  smtp-password: eW91ci1hcHAta2V5 # your-app-key
  jwt-secret: bXlTZWNyZXRLZXlteVNlY3JldEtleW15U2VjcmV0S2V5bXlTZWNyZXRLZXk= # base64 encoded secret
